// Canonical season data. Add a new object here when a new season starts.
// Cell values intentionally support trusted HTML for existing links and line breaks.
const seasonFields = [
  { key: "startDate", label: "Start date" },
  { key: "endDate", label: "End date" },
  { key: "endLeadTime", label: "End lead time" },
  { key: "duration", label: "Duration" },
  { key: "patch", label: "Patch" },
  { key: "theme", label: "Season theme" },
  { key: "ptr", label: "PTR" },
  { key: "ptrLeadTime", label: "PTR lead time" },
  { key: "barbarianSet", label: "Barb. free set" },
  { key: "crusaderSet", label: "Crus. free set" },
  { key: "demonHunterSet", label: "DH free set" },
  { key: "monkSet", label: "Monk free set" },
  { key: "necromancerSet", label: "Necro free set" },
  { key: "witchDoctorSet", label: "WD free set" },
  { key: "wizardSet", label: "Wizard free set" },
  { key: "conquest1", label: "Conquest 1" },
  { key: "conquest2", label: "Conquest 2" },
  { key: "conquest3", label: "Conquest 3" },
  { key: "conquest4", label: "Conquest 4" },
  { key: "conquest5", label: "Conquest 5" },
  { key: "portraitReward", label: "Reward: Portrait" },
  { key: "cosmeticReward", label: "Reward:<br>Cosmetic" },
];

const seasons = [
  {
    number: 1,
    values: {
      startDate: "29 Aug 2014",
      endDate: "03 Feb 2015",
      duration: "159 days",
      patch: "<small><a href=\"https://us.battle.net/d3/en/blog/15487814/patch-210-now-live-8-26-2014\" target=\"_blank\">2.1.0</a>, <a href=\"https://us.battle.net/d3/en/blog/16043922/patch-211-now-live-9-23-2014\" target=\"_blank\">2.1.1</a>, <a href=\"https://us.battle.net/d3/en/blog/17561388/patch-212-now-live-1-13-2015\" target=\"_blank\">2.1.2</a></small>",
      theme: "-",
      ptr: "(Multiple)",
      ptrLeadTime: "-",
      barbarianSet: "-",
      crusaderSet: "-",
      demonHunterSet: "-",
      monkSet: "-",
      necromancerSet: "-",
      witchDoctorSet: "-",
      wizardSet: "-",
      conquest1: "It's A Marathon",
      conquest2: "Sprinter",
      conquest3: "Race To The Top",
      conquest4: "<small>Now You've Done It</small>",
      conquest5: "Death Gets Got",
      portraitReward: "-",
      cosmeticReward: "Banner:<br>Eye/Teeth",
    },
  },
  {
    number: 2,
    values: {
      startDate: "13 Feb 2015",
      endDate: "05 Apr 2015",
      duration: "52 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/17561388/patch-212-now-live-1-13-2015\" target=\"_blank\">2.1.2</a>",
      theme: "-",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "-",
      crusaderSet: "-",
      demonHunterSet: "-",
      monkSet: "-",
      necromancerSet: "-",
      witchDoctorSet: "-",
      wizardSet: "-",
      conquest1: "<small>It's A Marathon</small>",
      conquest2: "Sprinter",
      conquest3: "Avarice",
      conquest4: "Boss Mode",
      conquest5: "Language",
      portraitReward: "-",
      cosmeticReward: "Banner:<br>Leaves",
    },
  },
  {
    number: 3,
    values: {
      startDate: "10 Apr 2015",
      endDate: "23 Aug 2015",
      duration: "136 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/18642492/patch-220-now-live-4-7-2015\" target=\"_blank\">2.2.0</a>",
      theme: "-",
      ptr: "<a href=\"http://www.diablofans.com/blizz-tracker/topic/58696-patch-2-2-0-ptr-now-available\" target=\"_blank\">26 Feb 2015</a>",
      ptrLeadTime: "43 days",
      barbarianSet: "-",
      crusaderSet: "-",
      demonHunterSet: "-",
      monkSet: "-",
      necromancerSet: "-",
      witchDoctorSet: "-",
      wizardSet: "-",
      conquest1: "<small>On A Good Day</small>",
      conquest2: "Sprinter",
      conquest3: "Avarice",
      conquest4: "The Thrill",
      conquest5: "Curses!",
      portraitReward: "Diablo",
      cosmeticReward: "Pennant:<br>Diablo 3",
    },
  },
  {
    number: 4,
    values: {
      startDate: "28 Aug 2015",
      endDate: "30 Dec 2015",
      duration: "125 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/19859662/patch-230-now-live-8-25-2015\" target=\"_blank\">2.3.0</a>",
      theme: "-",
      ptr: "<a href=\"http://www.diablofans.com/news/48457-2-3-0-ptr-patch-notes-are-live\" target=\"_blank\">30 Jun 2015</a>",
      ptrLeadTime: "59 days",
      barbarianSet: "-",
      crusaderSet: "-",
      demonHunterSet: "-",
      monkSet: "-",
      necromancerSet: "-",
      witchDoctorSet: "-",
      wizardSet: "-",
      conquest1: "<small>On A Good Day</small>",
      conquest2: "Divinity",
      conquest3: "The Thrill",
      conquest4: "Boss Mode",
      conquest5: "<small>Speed Demon</small>",
      portraitReward: "<small>Dragon Heads</small>",
      cosmeticReward: "Pet:<br>Frost Hound",
    },
  },
  {
    number: 5,
    values: {
      startDate: "15 Jan 2016",
      endDate: "15 Apr 2016",
      duration: "92 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/19998542/patch-240-now-live-1-12-2016\" target=\"_blank\">2.4.0</a>",
      theme: "-",
      ptr: "<a href=\"http://www.diablofans.com/blizz-tracker/topic/60870-patch-2-4-0-ptr-now-available\" target=\"_blank\">11 Nov 2015</a>",
      ptrLeadTime: "65 days",
      barbarianSet: "Earth",
      crusaderSet: "Invoker",
      demonHunterSet: "Shadow",
      monkSet: "Sunwuko",
      necromancerSet: "-",
      witchDoctorSet: "Jade",
      wizardSet: "Firebird",
      conquest1: "Avarice",
      conquest2: "Sprinter",
      conquest3: "The Thrill",
      conquest4: "Years of War",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "Greyhollow",
      cosmeticReward: "Pet:<br>Old Growth",
    },
  },
  {
    number: 6,
    values: {
      startDate: "29 Apr 2016",
      endDate: "22 Jul 2016",
      duration: "85 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/20099649/patch-241-now-live-4-26-2016\" target=\"_blank\">2.4.1</a>",
      theme: "-",
      ptr: "<a href=\"http://www.diablofans.com/news/48672-ptr-2-4-1-now-available-patch-notes\" target=\"_blank\">8 Mar 2016</a>",
      ptrLeadTime: "52 days",
      barbarianSet: "Raekor",
      crusaderSet: "Akkhan",
      demonHunterSet: "Marauder",
      monkSet: "Inna",
      necromancerSet: "-",
      witchDoctorSet: "Zuni",
      wizardSet: "DMO",
      conquest1: "<small>On A Good Day</small>",
      conquest2: "Divinity",
      conquest3: "Curses!",
      conquest4: "Boss Mode",
      conquest5: "<small>Speed Demon</small>",
      portraitReward: "Blood Shard",
      cosmeticReward: "Pennant:<br>Samhain",
    },
  },
  {
    number: 7,
    values: {
      startDate: "05 Aug 2016",
      endDate: "14 Oct 2016",
      duration: "70 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/20210379/patch-242-now-live-8-2-2016\" target=\"_blank\">2.4.2</a>",
      theme: "-",
      ptr: "<a href=\"http://www.diablofans.com/news/48765-new-ptr-patch-datamined-2-4-2-build-38044\" target=\"_blank\">28 Jun 2016</a>",
      ptrLeadTime: "38 days",
      barbarianSet: "Wastes",
      crusaderSet: "Roland",
      demonHunterSet: "UE",
      monkSet: "Raiment",
      necromancerSet: "-",
      witchDoctorSet: "Helltooth",
      wizardSet: "Tal Rasha",
      conquest1: "<small>On A Good Day</small>",
      conquest2: "Divinity",
      conquest3: "The Thrill",
      conquest4: "Avarice",
      conquest5: "Sprinter",
      portraitReward: "Frost",
      cosmeticReward: "Pet:<br><small>Dream or Piers</small>",
    },
  },
  {
    number: 8,
    values: {
      startDate: "21 Oct 2016",
      endDate: "30 Dec 2016",
      duration: "70 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/20210379/patch-242-now-live-8-2-2016\" target=\"_blank\">2.4.2</a>",
      theme: "-",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "IK",
      crusaderSet: "Light",
      demonHunterSet: "Natalya",
      monkSet: "Uliana",
      necromancerSet: "-",
      witchDoctorSet: "Arachyr",
      wizardSet: "Vyr",
      conquest1: "Boss Mode",
      conquest2: "Divinity",
      conquest3: "Curses!",
      conquest4: "Years of War",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "Pentagram",
      cosmeticReward: "Wings:<br><small>Anguish's Grasp</small>",
    },
  },
  {
    number: 9,
    values: {
      startDate: "06 Jan 2017",
      endDate: "17 Mar 2017",
      duration: "70 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/20426802/patch-243-now-live-1-4-2017\" target=\"_blank\">2.4.3</a>",
      theme: "-",
      ptr: "<a href=\"http://www.diablofans.com/news/48843-ptr-patch-2-4-3-datamined-and-patchnotes\" target=\"_blank\">8 Nov 2016</a>",
      ptrLeadTime: "59 days",
      barbarianSet: "Earth",
      crusaderSet: "Invoker",
      demonHunterSet: "Shadow",
      monkSet: "Sunwuko",
      necromancerSet: "-",
      witchDoctorSet: "Jade",
      wizardSet: "Firebird",
      conquest1: "Avarice",
      conquest2: "Sprinter",
      conquest3: "Curses!",
      conquest4: "The Thrill",
      conquest5: "<small>Speed Demon</small>",
      portraitReward: "<small>Pandemonium</small>",
      cosmeticReward: "Pet:<br>Rocky",
    },
  },
  {
    number: 10,
    values: {
      startDate: "31 Mar 2017",
      endDate: "23 Jun 2017",
      endLeadTime: "<a href=\"https://us.battle.net/d3/en/blog/20845156/season-10-ending-soon-6-9-2017\" target=\"_blank\">14 days</a>",
      duration: "85 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/20635663/patch-250-now-live-3-21-2017\" target=\"_blank\">2.5.0</a>",
      theme: "-",
      ptr: "<a href=\"http://www.diablofans.com/news/48867-patch-2-5-0-ptr-notes-now-live\" target=\"_blank\">1 Feb 2017</a>",
      ptrLeadTime: "58 days",
      barbarianSet: "Raekor",
      crusaderSet: "Akkhan",
      demonHunterSet: "Marauder",
      monkSet: "Inna",
      necromancerSet: "-",
      witchDoctorSet: "Zuni",
      wizardSet: "DMO",
      conquest1: "<small>On A Good Day</small>",
      conquest2: "Sprinter",
      conquest3: "Boss Mode",
      conquest4: "Years of War",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "Soulstone",
      cosmeticReward: "Pennant:<br>Cain",
    },
  },
  {
    number: 11,
    values: {
      startDate: "20 Jul 2017",
      endDate: "20 Oct 2017",
      endLeadTime: "<a href=\"https://www.pcgamesn.com/diablo-iii/diablo-3-season-12\" target=\"_blank\">11 days</a>",
      duration: "92 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/20845163/patch-260-now-live-6-27-2017\" target=\"_blank\">2.6.0</a>",
      theme: "-",
      ptr: "<a href=\"http://www.diablofans.com/news/48888-ptr-patch-2-6-0\" target=\"_blank\">11 Apr 2017</a>",
      ptrLeadTime: "100 days",
      barbarianSet: "Wastes",
      crusaderSet: "Roland",
      demonHunterSet: "UE",
      monkSet: "Raiment",
      necromancerSet: "Rathma",
      witchDoctorSet: "Helltooth",
      wizardSet: "Tal Rasha",
      conquest1: "Boss Mode",
      conquest2: "Divinity",
      conquest3: "Avarice",
      conquest4: "<small>Speed Demon</small>",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "<small>Treasure Goblin</small>",
      cosmeticReward: "Pet:<br><small>Emerald Serpent</small>",
    },
  },
  {
    number: 12,
    values: {
      startDate: "09 Nov 2017",
      endDate: "11 Feb 2018",
      duration: "94 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/21115840/patch-261-now-live-10-24-2017\" target=\"_blank\">2.6.1</a>",
      theme: "-",
      ptr: "<a href=\"http://www.diablofans.com/news/48928-patch-2-6-1-ptr-notes-new-items-and-significant\" target=\"_blank\">15 Aug 2017</a>",
      ptrLeadTime: "86 days",
      barbarianSet: "IK",
      crusaderSet: "Light",
      demonHunterSet: "Natalya",
      monkSet: "Uliana",
      necromancerSet: "Trag'Oul",
      witchDoctorSet: "Arachyr",
      wizardSet: "Vyr",
      conquest1: "Boss Mode",
      conquest2: "<small>On A Good Day</small>",
      conquest3: "The Thrill",
      conquest4: "Years of War",
      conquest5: "Curses!",
      portraitReward: "Heaven",
      cosmeticReward: "Wings:<br>Fiacla-Géar",
    },
  },
  {
    number: 13,
    values: {
      startDate: "23 Feb 2018",
      endDate: "03 Jun 2018",
      endLeadTime: "<a href=\"https://blizzardwatch.com/2018/05/21/diablo-3-season-13-ends-june-3-season-14-begins-june-15/\" target=\"_blank\">13 days</a>",
      duration: "100 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/21115840/patch-261-now-live-10-24-2017\" target=\"_blank\">2.6.1</a>",
      theme: "-",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "Earth",
      crusaderSet: "Invoker",
      demonHunterSet: "Shadow",
      monkSet: "Sunwuko",
      necromancerSet: "Inarius",
      witchDoctorSet: "Jade",
      wizardSet: "Firebird",
      conquest1: "Divinity",
      conquest2: "Sprinter",
      conquest3: "The Thrill",
      conquest4: "Curses!",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "Imperius",
      cosmeticReward: "Pet:<br>Blaine's Bear",
    },
  },
  {
    number: 14,
    values: {
      startDate: "15 Jun 2018",
      endDate: "16 Sep 2018",
      endLeadTime: "<a href=\"https://diablo.4fansites.de/news%2C12631%2CSeason-14-Ende-und-Season-15-Start-Termin.html\" target=\"_blank\">16 days</a>",
      duration: "93 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/21115840/patch-261-now-live-10-24-2017\" target=\"_blank\">2.6.1</a>",
      theme: "Greed",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "Raekor",
      crusaderSet: "Akkhan",
      demonHunterSet: "Marauder",
      monkSet: "Inna",
      necromancerSet: "Pest.",
      witchDoctorSet: "Zuni",
      wizardSet: "DMO",
      conquest1: "Avarice",
      conquest2: "Divinity",
      conquest3: "<small>On A Good Day</small>",
      conquest4: "<small>Speed Demon</small>",
      conquest5: "Years of War",
      portraitReward: "Tal Rasha",
      cosmeticReward: "Pennant:<br>Tyrael",
    },
  },
  {
    number: 15,
    values: {
      startDate: "21 Sep 2018",
      endDate: "06 Jan 2019",
      duration: "107 days",
      patch: "<a href=\"https://us.battle.net/d3/en/blog/21115840/patch-261-now-live-10-24-2017\" target=\"_blank\">2.6.1</a>",
      theme: "<small>Horadrim Boon</small>",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "Wastes",
      crusaderSet: "Roland",
      demonHunterSet: "UE",
      monkSet: "Raiment",
      necromancerSet: "Rathma",
      witchDoctorSet: "Helltooth",
      wizardSet: "Tal Rasha",
      conquest1: "Avarice",
      conquest2: "Sprinter",
      conquest3: "The Thrill",
      conquest4: "Boss Mode",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "<small>Eternal Conflict</small>",
      cosmeticReward: "Pet:<br>Belphegor",
    },
  },
  {
    number: 16,
    values: {
      startDate: "18 Jan 2019",
      endDate: "12 May 2019",
      endLeadTime: "<a href=\"https://news.blizzard.com/en-gb/article/22976066/season-17-the-season-of-nightmares-is-now-live\" target=\"_blank\">2 days</a>",
      duration: "114 days",
      patch: "<a href=\"https://us.diablo3.com/en/blog/22863534/patch-264-now-live-1-15-2019\" target=\"_blank\">2.6.4</a>",
      theme: "Grandeur",
      ptr: "<a href=\"https://www.reddit.com/r/diablo3/comments/9z9v4e/264_ptr_is_live_as_of_900am/\" target=\"_blank\">22 Nov 2018</a>",
      ptrLeadTime: "46 days",
      barbarianSet: "IK",
      crusaderSet: "Light",
      demonHunterSet: "Natalya",
      monkSet: "Uliana",
      necromancerSet: "Trag'Oul",
      witchDoctorSet: "Arachyr",
      wizardSet: "Vyr",
      conquest1: "Boss Mode",
      conquest2: "<small>On A Good Day</small>",
      conquest3: "Curses!",
      conquest4: "Years of War",
      conquest5: "<small>Speed Demon</small>",
      portraitReward: "<small>Call to Adv.</small>",
      cosmeticReward: "Wings:<br><small>W. of Lempo</small>",
    },
  },
  {
    number: 17,
    values: {
      startDate: "17 May 2019",
      endDate: "18 Aug 2019",
      endLeadTime: "<a href=\"https://us.forums.blizzard.com/en/d3/t/season-17-ends-august-18-s18-begins-8-23/1088\" target=\"_blank\">16 days</a>",
      duration: "93 days",
      patch: "<a href=\"https://us.diablo3.com/en/blog/22989462/patch-265-now-live-5-14-2019\" target=\"_blank\">2.6.5</a>",
      theme: "LoN",
      ptr: "<a href=\"https://www.reddit.com/r/Diablo/comments/b9umxs/patch_265_ptr_is_now_live/\" target=\"_blank\">5 Apr 2019</a>",
      ptrLeadTime: "42 days",
      barbarianSet: "Earth",
      crusaderSet: "Invoker",
      demonHunterSet: "Shadow",
      monkSet: "Sunwuko",
      necromancerSet: "Inarius",
      witchDoctorSet: "Jade",
      wizardSet: "Firebird",
      conquest1: "Avarice",
      conquest2: "Sprinter",
      conquest3: "The Thrill",
      conquest4: "Years of War",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "Greyhollow",
      cosmeticReward: "Wings:<br><small>Galactic Wings</small>",
    },
  },
  {
    number: 18,
    values: {
      startDate: "23 Aug 2019",
      endDate: "10 Nov 2019",
      duration: "79 days",
      patch: "<a href=\"https://us.diablo3.com/en/blog/23093788/patch-266-is-now-live-8-20-2019\" target=\"_blank\">2.6.6</a>",
      theme: "Triune",
      ptr: "<a href=\"https://www.diablofans.com/news/49115-patch-2-6-6-ptr-now-available\" target=\"_blank\">25 Jul 2019</a>",
      ptrLeadTime: "29 days",
      barbarianSet: "Raekor",
      crusaderSet: "Akkhan",
      demonHunterSet: "Marauder",
      monkSet: "Inna",
      necromancerSet: "Pest.",
      witchDoctorSet: "Zuni",
      wizardSet: "DMO",
      conquest1: "<small>On A Good Day</small>",
      conquest2: "Divinity",
      conquest3: "Boss Mode",
      conquest4: "<small>Speed Demon</small>",
      conquest5: "Curses!",
      portraitReward: "<small>Blood Shard</small>",
      cosmeticReward: "Pennant:<br>Samhain",
    },
  },
  {
    number: 19,
    values: {
      startDate: "22 Nov 2019",
      endDate: "01 Mar 2020",
      endLeadTime: "<a href=\"https://us.forums.blizzard.com/en/d3/t/season-19-ends-march-1/12756\" target=\"_blank\">16 days</a>",
      duration: "100 days",
      patch: "<a href=\"https://us.diablo3.com/en/blog/23220967/patch-267-now-live-11-12-2019\" target=\"_blank\">2.6.7</a>",
      theme: "<small>Eternal Confl.</small>",
      ptr: "<a href=\"https://www.diablofans.com/news/49133-patch-2-6-7-season-19-preview\" target=\"_blank\">19 Oct 2019</a>",
      ptrLeadTime: "34 days",
      barbarianSet: "Wastes",
      crusaderSet: "Roland",
      demonHunterSet: "UE",
      monkSet: "Raiment",
      necromancerSet: "Rathma",
      witchDoctorSet: "Helltooth",
      wizardSet: "Tal Rasha",
      conquest1: "Avarice",
      conquest2: "Sprinter",
      conquest3: "<small>On A Good Day</small>",
      conquest4: "Divinity",
      conquest5: "The Thrill",
      portraitReward: "Valor",
      cosmeticReward: "Pet:<br><small>Angelic Goblin</small>",
    },
  },
  {
    number: 20,
    values: {
      startDate: "13 Mar 2020",
      endDate: "21 Jun 2020",
      endLeadTime: "<a href=\"https://us.forums.blizzard.com/en/d3/t/season-20-ends-june-21st/18056\" target=\"_blank\">13 days</a>",
      duration: "100 days",
      patch: "<a href=\"https://us.diablo3.com/en/blog/23319443/patch-268-now-live-3-3-2020\" target=\"_blank\">2.6.8</a>",
      theme: "<small>Forb. Archives</small>",
      ptr: "<a href=\"https://www.diablofans.com/news/49177-patch-2-6-8-ptr-begins-2-6\" target=\"_blank\">06 Feb 2020</a>",
      ptrLeadTime: "36 days",
      barbarianSet: "IK",
      crusaderSet: "Light",
      demonHunterSet: "Natalya",
      monkSet: "Uliana",
      necromancerSet: "Trag'Oul",
      witchDoctorSet: "Arachyr",
      wizardSet: "Vyr",
      conquest1: "Boss Mode",
      conquest2: "Divinity",
      conquest3: "Curses!",
      conquest4: "Years of War",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "Teganze",
      cosmeticReward: "Pet:<br>Bat",
    },
  },
  {
    number: 21,
    values: {
      startDate: "03 Jul 2020",
      endDate: "06 Nov 2020",
      duration: "126 days",
      patch: "<a href=\"https://us.diablo3.com/en/blog/23420227/patch-269-ptr-has-ended-5-28-2020\" target=\"_blank\">2.6.9</a>",
      theme: "<small>Trials o/t Temp.</small>",
      ptr: "<a href=\"https://www.diablofans.com/news/49206-patch-2-6-9-ptr-begins-5-28\" target=\"_blank\">28 May 2020</a>",
      ptrLeadTime: "36 days",
      barbarianSet: "Earth",
      crusaderSet: "Invoker",
      demonHunterSet: "Shadow",
      monkSet: "Sunwuko",
      necromancerSet: "Inarius",
      witchDoctorSet: "Jade",
      wizardSet: "Firebird",
      conquest1: "Avarice",
      conquest2: "Sprinter",
      conquest3: "The Thrill",
      conquest4: "<small>Speed Demon</small>",
      conquest5: "Curses!",
      portraitReward: "Industrial",
      cosmeticReward: "Pet: Stup.<br>Contraption",
    },
  },
  {
    number: 22,
    values: {
      startDate: "20 Nov 2020",
      endDate: "28 Mar 2021",
      duration: "128 days",
      patch: "<a href=\"https://eu.diablo3.com/en-us/blog/23548757/season-22-shades-of-the-nephalem-patch-2610-now-live-11-6-2020\" target=\"_blank\">2.6.10</a>",
      theme: "<small>Shades o/t Neph.</small>",
      ptr: "<a href=\"https://www.diablofans.com/news/49229-ptr-for-patch-2-6-10-begins-october-1\" target=\"_blank\">01 Oct 2020</a>",
      ptrLeadTime: "36 days",
      barbarianSet: "Savages",
      crusaderSet: "Valor",
      demonHunterSet: "GoD",
      monkSet: "Justice",
      necromancerSet: "Carnival",
      witchDoctorSet: "Mundunugu",
      wizardSet: "Typhon's",
      conquest1: "<small>On A Good Day</small>",
      conquest2: "Sprinter",
      conquest3: "Boss Mode",
      conquest4: "Years of War",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "Lost Civ",
      cosmeticReward: "Pet: Book<br>of Cain",
    },
  },
  {
    number: 23,
    values: {
      startDate: "02 Apr 2021",
      endDate: "18 Jul 2021",
      duration: "107 days",
      patch: "<a href=\"https://us.diablo3.com/en-us/blog/23623166\" target=\"_blank\">2.7.0</a>",
      theme: "<small>Disc. of Sanct.</small>",
      ptr: "<a href=\"https://www.diablofans.com/news/49319-diablo-3-ptr-2-7-0-preview\" target=\"_blank\">23 Feb 2021</a>",
      ptrLeadTime: "38 days",
      barbarianSet: "Wastes",
      crusaderSet: "Roland",
      demonHunterSet: "UE",
      monkSet: "Raiment",
      necromancerSet: "Rathma",
      witchDoctorSet: "Helltooth",
      wizardSet: "Tal Rasha",
      conquest1: "Boss Mode",
      conquest2: "Divinity",
      conquest3: "Avarice",
      conquest4: "<small>Speed Demon</small>",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "<small>Chopping Block</small>",
      cosmeticReward: "Pet:<br><small>Lacuni Cub</small>",
    },
  },
  {
    number: 24,
    values: {
      startDate: "23 Jul 2021",
      endDate: "05 Dec 2021",
      duration: "135 days",
      patch: "<a href=\"https://eu.diablo3.com/en-us/blog/23695733/season-24-%7C-ethereal-memory-%7C-preview-blog-7-9-2021\" target=\"_blank\">2.7.1</a>",
      theme: "<small>Eth. Memory</small>",
      ptr: "<a href=\"https://www.diablofans.com/news/49473-diablo-iii-ptr-2-7-1-preview-blog\" target=\"_blank\">10 Jun 2021</a>",
      ptrLeadTime: "43 days",
      barbarianSet: "IK",
      crusaderSet: "Light",
      demonHunterSet: "Natalya",
      monkSet: "Uliana",
      necromancerSet: "Trag'Oul",
      witchDoctorSet: "Arachyr",
      wizardSet: "Vyr",
      conquest1: "Boss Mode",
      conquest2: "<small>On A Good Day</small>",
      conquest3: "The Thrill",
      conquest4: "Curses!",
      conquest5: "Years of War",
      portraitReward: "<small>Terror Resurr.</small>",
      cosmeticReward: "Pet: Lesser<br><small>Mummy Pet</small>",
    },
  },
  {
    number: 25,
    values: {
      startDate: "10 Dec 2021",
      endDate: "10 Apr 2022",
      duration: "121 days",
      patch: "<a href=\"https://news.blizzard.com/en-us/diablo3/23746130/season-25-the-lords-of-hell-ending-soon\" target=\"_blank\">2.7.2</a>",
      theme: "<small>Soul Shards</small>",
      ptr: "<a href=\"https://www.diablofans.com/news/49753-diablo-3-ptr-2-7-2-updated-november-12th\" target=\"_blank\">01 Nov 2021</a>",
      ptrLeadTime: "39 days",
      barbarianSet: "Earth",
      crusaderSet: "Invoker",
      demonHunterSet: "Shadow",
      monkSet: "Sunwuko",
      necromancerSet: "Inarius",
      witchDoctorSet: "Jade",
      wizardSet: "Firebird",
      conquest1: "Divinity",
      conquest2: "Sprinter",
      conquest3: "The Thrill",
      conquest4: "Curses!",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "<small>Pane of Tristram</small>",
      cosmeticReward: "Pet: Dark<br>Lordling",
    },
  },
  {
    number: 26,
    values: {
      startDate: "15 Apr 2022",
      endDate: "21 Aug 2022",
      duration: "128 days",
      patch: "<a href=\"https://news.blizzard.com/en-us/diablo3/23730897/diablo-3-ptr-2-7-2-has-ended\" target=\"_blank\">2.7.3</a>",
      theme: "<small>Echoing Nightm.</small>",
      ptr: "<a href=\"https://www.diablofans.com/news/50069-diablo-3-ptr-2-7-3-updated\" target=\"_blank\">07 Mar 2022</a>",
      ptrLeadTime: "35 days",
      barbarianSet: "Raekor",
      crusaderSet: "Akkhan",
      demonHunterSet: "Marauder",
      monkSet: "Inna",
      necromancerSet: "Pest.",
      witchDoctorSet: "Zuni",
      wizardSet: "DMO",
      conquest1: "Avarice",
      conquest2: "<small>On A Good Day</small>",
      conquest3: "Divinity",
      conquest4: "<small>Speed Demon</small>",
      conquest5: "Years of War",
      portraitReward: "<small>Rakki's Rememb.</small>",
      cosmeticReward: "Pet: Tooths.<br>Trooper",
    },
  },
  {
    number: 27,
    values: {
      startDate: "26 Aug 2022",
      endDate: "19 Feb 2023",
      duration: "177 days",
      patch: "<a href=\"https://news.blizzard.com/en-us/diablo3/23816414/season-27-light-s-calling-preview\" target=\"_blank\">2.7.4</a>",
      theme: "<small>Light's Calling</small>",
      ptr: "<a href=\"https://www.diablofans.com/news/50215-diablo-iii-ptr-2-7-4-preview\" target=\"_blank\">12 Jul 2022</a>",
      ptrLeadTime: "45 days",
      barbarianSet: "Wastes",
      crusaderSet: "Roland",
      demonHunterSet: "UE",
      monkSet: "Raiment",
      necromancerSet: "Rathma",
      witchDoctorSet: "Helltooth",
      wizardSet: "Tal Rasha",
      conquest1: "Avarice",
      conquest2: "Sprinter",
      conquest3: "The Thrill",
      conquest4: "Boss Mode",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "<small>Laurels of Knowl.</small>",
      cosmeticReward: "Pet: Corvus<br>Cadav.",
    },
  },
  {
    number: 28,
    values: {
      startDate: "24 Feb 2023",
      endDate: "10 Sep 2023",
      duration: "198 days",
      patch: "<a href=\"https://us.diablo3.blizzard.com/en-us/blog/23893119\" target=\"_blank\">2.7.5</a>",
      theme: "<small>Rites of Sanct.</small>",
      ptr: "<a href=\"https://www.diablofans.com/news/50431-diablo-iii-ptr-2-7-5-preview\" target=\"_blank\">31 Jan 2023</a>",
      ptrLeadTime: "24 days",
      barbarianSet: "Savages",
      crusaderSet: "Valor",
      demonHunterSet: "GoD",
      monkSet: "Justice",
      necromancerSet: "Carnival",
      witchDoctorSet: "Mundunugu",
      wizardSet: "Typhon's",
      conquest1: "Boss Mode",
      conquest2: "<small>On A Good Day</small>",
      conquest3: "Curses!",
      conquest4: "Years of War",
      conquest5: "<small>Speed Demon</small>",
      portraitReward: "<small>Primal Hunter</small>",
      cosmeticReward: "Pet: Taenin<br>the Tiny",
    },
  },
  {
    number: 29,
    values: {
      startDate: "15 Sep 2023",
      endDate: "07 Jan 2024",
      endLeadTime: "<a href=\"https://news.blizzard.com/en-us/article/24046224/season-30-the-lords-of-hell-preview-1-5-2024\" target=\"_blank\">2 days</a>",
      duration: "114 days",
      patch: "<a href=\"https://us.diablo3.blizzard.com/en-us/blog/23987087\" target=\"_blank\">2.7.6</a>",
      theme: "<small>Vis. of Enmity</small>",
      ptr: "<a href=\"https://us.diablo3.blizzard.com/en-us/blog/23987087\" target=\"_blank\">15 Aug 2023</a>",
      ptrLeadTime: "31 days",
      barbarianSet: "Earth",
      crusaderSet: "Invoker",
      demonHunterSet: "Shadow",
      monkSet: "Sunwuko",
      necromancerSet: "Inarius",
      witchDoctorSet: "Jade",
      wizardSet: "Firebird",
      conquest1: "Avarice",
      conquest2: "Sprinter",
      conquest3: "The Thrill",
      conquest4: "Years of War",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "<small>Mad King's Fav.</small>",
      cosmeticReward: "Pet: Quoth",
    },
  },
  {
    number: 30,
    values: {
      startDate: "12 Jan 2024",
      endDate: "07 Apr 2024",
      endLeadTime: "<a href=\"https://news.blizzard.com/en-us/article/24078323/season-31-season-of-the-forbidden-archives-preview\" target=\"_blank\">11 days</a>",
      duration: "86 days",
      patch: "<a href=\"https://us.diablo3.blizzard.com/en-us/blog/24046224/season-30-the-lords-of-hell-preview-1-5-2024\" target=\"_blank\">2.7.7</a>",
      theme: "<small>Lords of Hell</small>",
      ptr: "<a href=\"https://www.diablofans.com/news/50798-diablo-iii-ptr-2-7-7-now-live\" target=\"_blank\">7 Dec 2023</a>",
      ptrLeadTime: "36 days",
      barbarianSet: "Raekor",
      crusaderSet: "Akkhan",
      demonHunterSet: "Marauder",
      monkSet: "Inna",
      necromancerSet: "Pest.",
      witchDoctorSet: "Zuni",
      wizardSet: "DMO",
      conquest1: "<small>On A Good Day</small>",
      conquest2: "Divinity",
      conquest3: "Boss Mode",
      conquest4: "<small>Speed Demon</small>",
      conquest5: "Curses!",
      portraitReward: "<small>Blood Shard</small>",
      cosmeticReward: "-",
    },
  },
  {
    number: 31,
    values: {
      startDate: "12 Apr 2024",
      endDate: "07 Jul 2024",
      endLeadTime: "<a href=\"https://news.blizzard.com/en-us/article/24104599/season-32-ethereal-memory-preview\" target=\"_blank\">9 days</a>",
      duration: "86 days",
      patch: "<a href=\"https://news.blizzard.com/en-us/diablo3/24078323/season-31-season-of-the-forbidden-archives-preview\" target=\"_blank\">2.7.7</a>",
      theme: "<small>Forb. Archives</small>",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "Wastes",
      crusaderSet: "Roland",
      demonHunterSet: "UE",
      monkSet: "Raiment",
      necromancerSet: "Rathma",
      witchDoctorSet: "Helltooth",
      wizardSet: "Tal Rasha",
      conquest1: "<small>On A Good Day</small>",
      conquest2: "Divinity",
      conquest3: "Avarice",
      conquest4: "Sprinter",
      conquest5: "The Thrill",
      portraitReward: "Valor",
      cosmeticReward: "Pet:<br><small>Angelic Goblin</small>",
    },
  },
  {
    number: 32,
    values: {
      startDate: "12 Jul 2024",
      endDate: "20 Oct 2024",
      endLeadTime: "<a href=\"https://news.blizzard.com/en-us/article/24137819/season-33-shades-of-the-nephalem-preview\" target=\"_blank\">23 days</a>",
      duration: "100 days",
      patch: "<a href=\"https://us.diablo3.blizzard.com/en-us/blog/24104599/season-32-ethereal-memory-preview-6-28-2024\" target=\"_blank\">2.7.7</a>",
      theme: "<small>Eth. Memory</small>",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "IK",
      crusaderSet: "Light",
      demonHunterSet: "Natalya",
      monkSet: "Uliana",
      necromancerSet: "Trag'Oul",
      witchDoctorSet: "Arachyr",
      wizardSet: "Vyr",
      conquest1: "Boss Mode",
      conquest2: "Divinity",
      conquest3: "Curses!",
      conquest4: "Years of War",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "Teganze",
      cosmeticReward: "Pet:<br>Bat",
    },
  },
  {
    number: 33,
    values: {
      startDate: "25 Oct 2024",
      endDate: "19 Jan 2025",
      endLeadTime: "<a href=\"https://news.blizzard.com/en-us/article/24166297/season-34-lights-calling-preview\" target=\"_blank\">9 days</a>",
      duration: "86 days",
      patch: "<a href=\"https://news.blizzard.com/en-us/diablo3/24137819/season-33-shades-of-the-nephalem-preview\" target=\"_blank\">2.7.8</a>",
      theme: "<small>Shades o/t Neph.</small>",
      ptr: "<a href=\"https://us.diablo3.blizzard.com/en-us/blog/24135096/diablo-iii-ptr-278-has-concluded-9-13-2024\" target=\"_blank\">19 Sep 2024</a>",
      ptrLeadTime: "36 days",
      barbarianSet: "Earth",
      crusaderSet: "Invoker",
      demonHunterSet: "Shadow",
      monkSet: "Sunwuko",
      necromancerSet: "Inarius",
      witchDoctorSet: "Jade",
      wizardSet: "Firebird",
      conquest1: "Avarice",
      conquest2: "Sprinter",
      conquest3: "Curses!",
      conquest4: "<small>Speed Demon</small>",
      conquest5: "The Thrill",
      portraitReward: "<small>Pandemonium</small>",
      cosmeticReward: "Pet:<br>Rocky",
    },
  },
  {
    number: 34,
    values: {
      startDate: "31 Jan 2025",
      endDate: "01 Jun 2025",
      endLeadTime: "<a href=\"https://news.blizzard.com/en-us/article/24191146/season-35-eternal-conflict-preview\" target=\"_blank\">10 days</a>",
      duration: "121 days",
      patch: "<a href=\"https://news.blizzard.com/en-us/article/24166297/season-34-lights-calling-preview\" target=\"_blank\">2.8.0</a>",
      theme: "<small>Light's Calling</small>",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "Savages",
      crusaderSet: "Valor",
      demonHunterSet: "GoD",
      monkSet: "Justice",
      necromancerSet: "Carnival",
      witchDoctorSet: "Mundunugu",
      wizardSet: "Typhon's",
      conquest1: "<small>On A Good Day</small>",
      conquest2: "Sprinter",
      conquest3: "Boss Mode",
      conquest4: "Years of War",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "Soulstone",
      cosmeticReward: "Pennant:<br>Loremaster",
    },
  },
  {
    number: 35,
    values: {
      startDate: "05 Jun 2025",
      endDate: "07 Sep 2025",
      endLeadTime: "<a href=\"https://news.blizzard.com/en-gb/article/24231417/season-36-the-lords-of-hell-preview\" target=\"_blank\">9 days</a>",
      duration: "94 days",
      patch: "<a href=\"https://news.blizzard.com/en-us/article/24191146/season-35-eternal-conflict-preview\" target=\"_blank\">2.8.0</a>",
      theme: "<small>Eternal Conflict</small>",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "Wastes",
      crusaderSet: "Roland",
      demonHunterSet: "UE",
      monkSet: "Raiment",
      necromancerSet: "Rathma",
      witchDoctorSet: "Helltooth",
      wizardSet: "Tal Rasha",
      conquest1: "Boss Mode",
      conquest2: "Divinity",
      conquest3: "Avarice",
      conquest4: "<small>Speed Demon</small>",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "<small>Chopping Block</small>",
      cosmeticReward: "Pet:<br><small>Lacuni Cub</small>",
    },
  },
  {
    number: 36,
    values: {
      startDate: "12 Sep 2025",
      endDate: "30 Nov 2025",
      endLeadTime: "<a href=\"https://news.blizzard.com/en-us/article/24243442/season-37-the-forbidden-archives-preview\" target=\"_blank\">9 days</a>",
      duration: "79 days",
      patch: "<a href=\"https://news.blizzard.com/en-gb/article/24231417/season-36-the-lords-of-hell-preview\" target=\"_blank\">2.8.0</a>",
      theme: "<small>Lords of Hell</small>",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "IK",
      crusaderSet: "Light",
      demonHunterSet: "Natalya",
      monkSet: "Uliana",
      necromancerSet: "Trag'Oul",
      witchDoctorSet: "Arachyr",
      wizardSet: "Vyr",
      conquest1: "Boss Mode",
      conquest2: "<small>On A Good Day</small>",
      conquest3: "The Thrill",
      conquest4: "Curses!",
      conquest5: "Years of War",
      portraitReward: "<small>Terror Resurr.</small>",
      cosmeticReward: "Pet: Lesser<br><small>Mummy Pet</small>",
    },
  },
  {
    number: 37,
    values: {
      startDate: "05 Dec 2025",
      endDate: "22 Mar 2026",
      endLeadTime: "<a href=\"https://news.blizzard.com/en-us/article/24262572/season-38-ethereal-memory-preview\" target=\"_blank\">9 days</a>",
      duration: "105 days",
      patch: "<a href=\"https://news.blizzard.com/en-us/article/24243442/season-37-the-forbidden-archives-preview\" target=\"_blank\">2.8.0</a>",
      theme: "<small>Forb. Archives</small>",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "Earth",
      crusaderSet: "Invoker",
      demonHunterSet: "Shadow",
      monkSet: "Sunwuko",
      necromancerSet: "Inarius",
      witchDoctorSet: "Jade",
      wizardSet: "Firebird",
      conquest1: "Divinity",
      conquest2: "Sprinter",
      conquest3: "The Thrill",
      conquest4: "Curses!",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "Imperius",
      cosmeticReward: "Pet:<br>Blaine's Bear",
    },
  },
  {
    number: 38,
    values: {
      startDate: "27 Mar 2026",
      endDate: "21 Jun 2026",
      endLeadTime: "<a href=\"https://news.blizzard.com/en-gb/article/24287549/season-39-shades-of-the-nephalem-now-live\" target=\"_blank\">2 days</a>",
      duration: "86 days",
      patch: "<a href=\"https://news.blizzard.com/en-us/article/24262572/season-38-ethereal-memory-preview\" target=\"_blank\">2.8.0</a>",
      theme: "<small>Eth. Memory</small>",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "Raekor",
      crusaderSet: "Akkhan",
      demonHunterSet: "Marauder",
      monkSet: "Inna",
      necromancerSet: "Pest.",
      witchDoctorSet: "Zuni",
      wizardSet: "DMO",
      conquest1: "Avarice",
      conquest2: "<small>On A Good Day</small>",
      conquest3: "Divinity",
      conquest4: "<small>Speed Demon</small>",
      conquest5: "Years of War",
      portraitReward: "<small>Rakki's Rememb.</small>",
      cosmeticReward: "Pet: Tooths.<br>Trooper",
    },
  },
  {
    number: 39,
    values: {
      startDate: "26 Jun 2026",
      endDate: "27 Sep 2026",
      endLeadTime: "<a href=\"https://news.blizzard.com/en-us/article/24301510/season-40-lights-calling-preview\" target=\"_blank\">15 days</a>",
      duration: "93 days",
      patch: "<a href=\"https://news.blizzard.com/en-gb/article/24287549/season-39-shades-of-the-nephalem-now-live\" target=\"_blank\">2.8.0</a>",
      theme: "<small>Shades o/t Neph.</small>",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "Wastes",
      crusaderSet: "Roland",
      demonHunterSet: "UE",
      monkSet: "Raiment",
      necromancerSet: "Rathma",
      witchDoctorSet: "Helltooth",
      wizardSet: "Tal Rasha",
      conquest1: "Avarice",
      conquest2: "Sprinter",
      conquest3: "The Thrill",
      conquest4: "Boss Mode",
      conquest5: "<small>M. of the Univ.</small>",
      portraitReward: "<small>Eternal Conflict</small>",
      cosmeticReward: "Pet:<br>Belphegor",
    },
  },
  {
    number: 40,
    values: {
      startDate: "02 Oct 2026",
      endDate: "???",
      duration: "???",
      patch: "<a href=\"https://news.blizzard.com/en-us/article/24301510/season-40-lights-calling-preview\" target=\"_blank\">2.8.0</a>",
      theme: "<small>Light's Calling</small>",
      ptr: "(no PTR)",
      ptrLeadTime: "-",
      barbarianSet: "Savages",
      crusaderSet: "Valor",
      demonHunterSet: "GoD",
      monkSet: "Justice",
      necromancerSet: "Carnival",
      witchDoctorSet: "Mundunugu",
      wizardSet: "Typhon's",
      conquest1: "<small>Speed Demon</small>",
      conquest2: "<small>On A Good Day</small>",
      conquest3: "Boss Mode",
      conquest4: "Curses!",
      conquest5: "Years of War",
      portraitReward: "<small>Primal Hunter</small>",
      cosmeticReward: "Pet: Taennin<br>the Tiny",
    },
  },
];
